name: macvon_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  jose: ^0.1.2
  json_annotation: ^2.4.0 # json序列化和反序列化用的
  dio: ^3.0.4 # http请求用的
  fish_redux: ^0.2.2 # 状态管理用的
  shared_preferences: ^0.4.3
  fluttertoast: ^3.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pics/bank_zs.png
    - assets/tab_icon/tab_icon_budgets_d.png
    - assets/tab_icon/tab_icon_budgets_s.png
    - assets/tab_icon/tab_icon_more_d.png
    - assets/tab_icon/tab_icon_more_s.png
    - assets/tab_icon/tab_icon_transactions_d.png
    - assets/tab_icon/tab_icon_transactions_s.png
    - assets/tab_icon/tab_icon_wallet_d.png
    - assets/tab_icon/tab_icon_wallet_s.png
    - assets/more/funds.png
    - assets/more/more_btn_edit.png
    - assets/more/more_icon_alerts.png
    - assets/more/more_icon_login_options.png
    - assets/more/more_icon_logout.png
    - assets/more/more_icon_requests.png
    - assets/more/more_icon_sendfunds.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Farrington
      fonts:
        - asset: assets/fonts/Farrington-7B.ttf
    - family: IconFont
      fonts:
        - asset: assets/fonts/IconFont.ttf
    - family: AntdIcons
      fonts:
        - asset: assets/fonts/AntdIcons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
